#!/usr/bin/env bash
# Single source of truth for Cloud Run config: .env
#
# 1. Push sensitive keys to GCP Secret Manager.
# 2. Regenerate config/docker/cloudrun-env.yaml with non-secret keys,
#    auto-applying production overrides (APP_ENV, LOG_LEVEL, ALLOWED_ORIGINS).
#
# Idempotent. Bash 3.2 compatible (macOS default).
# Custom line-based parser preserves literal values (e.g. JSON arrays).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_YAML="$ROOT/config/docker/cloudrun-env.yaml"
PROD_FRONTEND_URL="https://prop-os-delta.vercel.app"

[ -f "$ENV_FILE" ] || { echo "ERROR: $ENV_FILE missing" >&2; exit 1; }

# Reads file line-by-line, sets KV_<KEY>=<value> shell vars.
# Preserves literal value after = (only strips matched outer single/double quotes).
read_env() {
  local file="$1"
  [ -f "$file" ] || return 0
  local line k v
  while IFS= read -r line || [ -n "$line" ]; do
    [[ -z "${line// }" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      k="${BASH_REMATCH[1]}"
      v="${BASH_REMATCH[2]}"
      if [[ "$v" =~ ^\"(.*)\"$ ]]; then v="${BASH_REMATCH[1]}"; fi
      if [[ "$v" =~ ^\'(.*)\'$ ]]; then v="${BASH_REMATCH[1]}"; fi
      eval "KV_$k=\$v"
    fi
  done < "$file"
}

kv() { local var="KV_$1"; printf '%s' "${!var:-}"; }

read_env "$ENV_FILE"

# === PROD OVERRIDES (applied automatically when generating cloudrun-env.yaml) ===
# .env has dev values; these substitute the prod-correct ones.
KV_APP_ENV="production"
KV_LOG_LEVEL="info"
KV_ALLOWED_ORIGINS='["'"$PROD_FRONTEND_URL"'"]'

# Sensitive keys -> Secret Manager
SECRETS=(
  SUPABASE_URL
  SUPABASE_ANON_KEY
  SUPABASE_SERVICE_ROLE_KEY
  VAPID_PUBLIC_KEY
  VAPID_PRIVATE_KEY
  CEREBRAS_API_KEY
  GROQ_API_KEY
  ANTHROPIC_API_KEY
  OPENAI_API_KEY
)

# Non-secret keys -> cloudrun-env.yaml (committed to git)
NON_SECRETS=(
  APP_ENV
  LOG_LEVEL
  ALLOWED_ORIGINS
  VAPID_CONTACT_EMAIL
  ANITA_PROVIDER
  ANITA_MODEL
  ANITA_FALLBACK_PROVIDER
  ANITA_TRANSCRIBE_PROVIDER
  ANITA_DAILY_BUDGET_USD
  ANITA_MAX_TOOL_CALLS_PER_TURN
  ANITA_TURN_TIMEOUT_SECONDS
  ANITA_STRICT_JSON_RETRY
)

if [ "${SKIP_SECRETS:-}" = "1" ]; then
  echo "=== SKIP_SECRETS=1 — skipping Secret Manager sync ==="
else
  echo "=== syncing secrets to GCP Secret Manager ==="
  for key in "${SECRETS[@]}"; do
    value="$(kv "$key")"
    if [ -z "$value" ]; then
      echo "skip      $key (empty in .env)"
      continue
    fi
    secret_name=$(echo "$key" | tr '[:upper:]_' '[:lower:]-')
    if gcloud secrets describe "$secret_name" >/dev/null 2>&1; then
      current=$(gcloud secrets versions access latest --secret="$secret_name" 2>/dev/null || echo "")
      if [ "$current" = "$value" ]; then
        echo "unchanged $secret_name"
      else
        printf '%s' "$value" | gcloud secrets versions add "$secret_name" --data-file=- >/dev/null
        echo "updated   $secret_name"
      fi
    else
      printf '%s' "$value" | gcloud secrets create "$secret_name" \
        --data-file=- --replication-policy=automatic >/dev/null
      echo "created   $secret_name"
    fi
  done
fi

echo ""
echo "=== regenerating $OUT_YAML (with prod overrides) ==="
{
  echo "# AUTO-GENERATED by scripts/sync_cloud_env.sh — do not edit manually."
  echo "# Source: .env. Prod overrides applied: APP_ENV, LOG_LEVEL, ALLOWED_ORIGINS."
  echo "# Run: make deploy-secrets-sync"
  for key in "${NON_SECRETS[@]}"; do
    value="$(kv "$key")"
    [ -z "$value" ] && continue
    escaped="${value//\'/\'\'}"
    printf "%s: '%s'\n" "$key" "$escaped"
  done
} > "$OUT_YAML"

echo "wrote $OUT_YAML"
echo ""
echo "Next: git add + commit + push (auto-deploys via Cloud Build trigger)."
