-- =====================================================================
-- interaction_targets: the PROJECT/OPPORTUNITY branch never required its id.
--
-- 20240101000024:96-101 wrote the CHECK when only property_id and place_id
-- existed; project_id and opportunity_id were added later (…0027, …0028) and
-- the constraint was never revisited. Its third branch is therefore
-- unconditional -- `target_kind IN ('PROJECT','OPPORTUNITY')` passes with both
-- columns NULL, so a target row can point at nothing.
--
-- The constraint name is autogenerated, so it is located by definition rather
-- than by name -- same approach as 20240601000033_normalize_source_checks.sql.
--
-- Pre-flight run before writing this: 0 rows violate the tightened rule
-- (the table is empty today), so it can be added VALID rather than NOT VALID.
-- The writer already complies: executors.py:130-137 always sets project_id
-- when target_kind is PROJECT.
-- =====================================================================

DO $$
DECLARE
  v_name TEXT;
  v_bad  BIGINT;
BEGIN
  SELECT count(*) INTO v_bad
    FROM public.interaction_targets
   WHERE (target_kind = 'PROJECT'     AND project_id     IS NULL)
      OR (target_kind = 'OPPORTUNITY' AND opportunity_id IS NULL);

  IF v_bad > 0 THEN
    RAISE EXCEPTION 'refusing to tighten: % existing rows would violate the new CHECK', v_bad
      USING HINT = 'clean the rows first, or add the constraint NOT VALID and validate later';
  END IF;

  SELECT conname INTO v_name
    FROM pg_constraint
   WHERE conrelid = 'public.interaction_targets'::regclass
     AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%target_kind%';

  IF v_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.interaction_targets DROP CONSTRAINT %I', v_name);
  END IF;

  ALTER TABLE public.interaction_targets
    ADD CONSTRAINT interaction_targets_kind_id_check CHECK (
         (target_kind = 'PROPERTY'    AND property_id    IS NOT NULL)
      OR (target_kind = 'PLACE'       AND place_id       IS NOT NULL)
      OR (target_kind = 'PROJECT'     AND project_id     IS NOT NULL)
      OR (target_kind = 'OPPORTUNITY' AND opportunity_id IS NOT NULL)
    );
END
$$;
